springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /**

spring:
  mvc:
    static-path-pattern: /res
  mail:
    host: smtp.dooray.com
    port: 587
    username: passlogin@atoncorp.com
    password: ats4273*
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
    cache: false
    enabled: true


  datasource:
    #    driverClassName: org.mariadb.jdbc.Driver
    #    url: jdbc:mariadb://localhost:3306/aton_final_project?allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/aton_final_project?allowMultiQueries=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        show_sql: true #show sql

  logging:
    level:
      org.hibernate:
        type.descriptor.sql: trace
        SQL: DEBUG

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      #      location: C:\homework\aton_final_project\src\main\resources\uploaded_files
      location: src\main\resources\uploaded_files

mybatis:
  #  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.example.aton_final_project.model
  mapper-locations: mybatis/mapper/**/*.xml

server:
  servlet:
    session:
      timeout: 600
    register-default-servlet: true
